### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by ritwikmishra** [Open-Speech-EkStep/ekstep-language-identification#1]
It is giving me CUDA out of memory error on GTX 2080 and 1080 (both 10+ GB cards) (single-GPU run). What is the recommended GPU size? or What are the specifications of the GPU on which it is trained originally?

My total training data for all classes is 130 hours of speech

**Comment by agupta54** [comment]
Hi @ritwikmishra can you try to check your batch_size while training? Our audio data was of 16000 sample rate. It is possible that you are using a higher sampling rate, which consumes more GPU memory while loading data. 
We trained on a single 16 GB Tesla T4.
